name:  Deploy

on:
  push:
    branches: [ main ]

jobs:
        
  deploy-dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to dev using ${{ secrets.mysecret-dev }}
      
  deploy-qa:
    name: Deploy to qa
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to qa using ${{ secrets.mysecret-qa }}
      
  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging using ${{ secrets.mysecret-stag }}
        
  deploy-production:
    name: Deploy to production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production using ${{ secrets.mysecret-prod }}
